### ISSUE TITLE
pytest run one test function, module's setup and tear-down function would run multi-times.

### ISSUE THREAD

**Issue by shadow1163** [pytest-dev/pytest-rerunfailures#56] opened 2018-01-02 09:18 UTC
if test file just have one test function, the module's setup and tear-down function would run multi-times.
log as follow:
```
/work/python$ py.test -v -s --reruns 5 test_random.py 
=========================================================================================== test session starts ============================================================================================
platform linux2 -- Python 2.7.14, pytest-3.3.1, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python
cachedir: .cache
rootdir: ~/work/python, inifile:
plugins: rerunfailures-4.0, allure-adaptor-1.7.9
collected 1 item                                                                                                                                                                                           

test_random.py::test_example 
random "module"

random "setup"

random

random "teardown function"

random "teardown module"
RERUN                                                                                                                                                                   [100%]
test_random.py::test_example 
random "module"

random "setup"

random

random "teardown function"

random "teardown module"
RERUN                                                                                                                                                                   [200%]
test_random.py::test_example 
random "module"

random "setup"

random

random "teardown function"

random "teardown module"
RERUN                                                                                                                                                                   [300%]
test_random.py::test_example 
random "module"

random "setup"

random

random "teardown function"

random "teardown module"
PASSED                                                                                                                                                                  [400%]

==================================================================================== 1 passed, 3 rerun in 0.02 seconds =====================================================================================
```
I think the module's setup and tear-down function should be run one time.

**Comment by sallner** [comment] 2018-01-04 11:43
@shadow1163 Thanks for reporting this issue. It seems to me like this is in a sense a duplicate of #51. This puts the issue a bit higher on the to-do list. Would you have some capacities to work on that?

**Comment by bstaletic** [comment] 2020-10-12 09:35
Hello. [ycmd](/ycm-core/ycmd) has just hit this problem. This basically makes running a single flaky test impossible, as the fixture doesn't persist.

**Comment by icemac** [comment] 2021-12-03 06:57
Closing as duplicate of #51.

**Closed by icemac** 2021-12-03 06:57 UTC
