### ISSUE TITLE
breaks with pytest 5.4

### ISSUE THREAD

**Issue by mayou36** [pytest-dev/pytest-rerunfailures#105] opened 2020-03-16 08:10 UTC
It seems as if pytest 5.4 breaks rerunfailures and produces an internal error.
5.3 seems to work.

The error produced (the end of it, full stacktrace e.g. here: https://travis-ci.org/github/zfit/zfit/jobs/662817882#L400) is:
```
-packages/pytest_rerunfailures.py", line 194, in pytest_runtest_protocol
INTERNALERROR>     _remove_cached_results_from_failed_fixtures(item)
INTERNALERROR>   File "/home/jonas/anaconda3/envs/zfit37debug/lib/python3.7/site-packages/pytest_rerunfailures.py", line 135, in _remove_cached_results_from_failed_fixtures
INTERNALERROR>     result, cache_key, err = getattr(fixture_def, cached_result)
INTERNALERROR> TypeError: cannot unpack non-iterable NoneType object
```

**Comment by icemac** [comment] 2020-03-16 13:48
This issue is a duplicate of #103.

**Closed by icemac** 2020-03-16 13:48 UTC
