### ISSUE TITLE
session scope Fixture will run again when the last testcase fail

### ISSUE THREAD

**Issue by wanglinwu2019** [pytest-dev/pytest-rerunfailures#174] opened 2021-11-30 03:41 UTC
Here is my test module:
```
def test_case1():
    print("this is cas1")
    assert True

def test_case2():
    print("this is cas2")
    assert True

def test_case3():
    print("this is cas3")
    assert False
```
**and here is my fixture in conftest.py:**
```
@pytest.fixture(scope='session', autouse=True)
def sessionFixture():
    print("sessionFixture before yield")
    yield
    print("sessionFixture after yield")
```
Here is output:
============================= test session starts =============================
platform win32 -- Python 3.10.0, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: D:\project\pytest_test, configfile: pytest.ini, testpaths: test_rerun.py
plugins: rerunfailures-10.2
collected 3 items

test_rerun.py sessionFixture before yield
this is cas1
.this is cas2
.this is cas3
sessionFixture after yield
RsessionFixture before yield
this is cas3
sessionFixture after yield
F

================================== FAILURES ===================================
............
I found only  the failure of the last testcase can cause the fixture run twice. when others testcase fail, for example test_case1 or test_case2, it works no issue.
There is no other plugin. Versions:
pytest-rerunfailures   10.2
pytest                         6.2.5
python                       3.10.0

**Comment by icemac** [comment] 2021-12-03 06:56
Closing as duplicate of #51.

**Closed by icemac** 2021-12-03 06:56 UTC
