### ISSUE TITLE
The 4.2 version bug

### ISSUE THREAD

**Issue by Yanci516** [pytest-dev/pytest-rerunfailures#72] opened 2018-10-27 02:44 UTC
In version 4.2, when a file has multiple use cases, the first use case fails and retries without tearDownClass execution and runs setUpClass directly; in version 4.1, this situation does not execute setUpClass

**Comment by sallner** [comment] 2018-11-20 15:18
@YancyGo could you please provide a minimal example so that I can reproduce this behaviour?

**Comment by sallner** [comment] 2019-01-08 10:10
@YancyGo Does this issue still persist? In that case could you please provide a minimal example? Otherwise I will close this issue soon.

**Comment by sallner** [comment] 2019-02-07 08:07
I close this bug due to a lack of feedback.

**Closed by sallner** 2019-02-07 08:07 UTC
Labels: help wanted
