### ISSUE TITLE
Random seed

### ISSUE THREAD

**Issue by caiolopes** [pytest-dev/pytest-rerunfailures#125] opened 2020-08-05 14:40 UTC
Should this library change the seed in order to make random dependency errors disappear on rerun?

```
 pytest -vv --reruns 10 --reruns-delay 1 tests/test_dummy.py
Test session starts (platform: linux, Python 3.7.8, pytest 4.6.9, pytest-sugar 0.9.2)
cachedir: .pytest_cache
Django settings: settings.test (from command line option)
Using --randomly-seed=1596637848
benchmark: 3.2.2 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
metadata: {'Python': '3.7.8', 'Platform': 'Linux-4.19.76-linuxkit-x86_64-with-debian-10.4', 'Packages': {'pytest': '4.6.9', 'py': '1.8.0', 'pluggy': '0.13.1'}, 'Plugins': {'repeat': '0.8.0', 'profiling': '1.7.0', 'xdist': '1.29.0', 'forked': '1.3.0', 'sugar': '0.9.2', 'Faker': '4.1.1', 'cov': '2.5.1', 'django': '3.5.1', 'celery': '4.4.2', 'mock': '1.10.4', 'html': '1.19.0', 'randomly': '1.2.3', 'rerunfailures': '7.0', 'benchmark': '3.2.2', 'freezegun': '0.3.0.post1', 'metadata': '1.10.0'}}
rootdir: /opt/app/app, inifile: pytest.ini
plugins: repeat-0.8.0, profiling-1.7.0, xdist-1.29.0, forked-1.3.0, sugar-0.9.2, Faker-4.1.1, cov-2.5.1, django-3.5.1, celery-4.4.2, mock-1.10.4, html-1.19.0, randomly-1.2.3, rerunfailures-7.0, benchmark-3.2.2, freezegun-0.3.0.post1, metadata-1.10.0
collecting ...


―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― test_dummy ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    def test_dummy():
        a = random()

        print(a)

>       assert a == 1
E       assert 0.7776721062540077 == 1
E         -0.7776721062540077
E         +1

tests/test_dummy.py:8: AssertionError
----------------------------------- Captured stdout call ---------
0.7776721062540077
----------------------------------- Captured stdout call ---------
0.7776721062540077
----------------------------------- Captured stdout call ---------
0.7776721062540077
----------------------------------- Captured stdout call ---------
0.7776721062540077
----------------------------------- Captured stdout call ---------
0.7776721062540077
----------------------------------- Captured stdout call ---------
0.7776721062540077
----------------------------------- Captured stdout call ---------
0.7776721062540077
----------------------------------- Captured stdout call ---------
0.7776721062540077
----------------------------------- Captured stdout call ---------
0.7776721062540077
----------------------------------- Captured stdout call ---------
0.7776721062540077
----------------------------------- Captured stdout call ---------
0.7776721062540077

 tests/test_dummy.py::test_dummy ⨯                                                                                                                                                                                           100% ██████████

Results (10.96s):
       1 failed
         - tests/test_dummy.py:3 test_dummy
      10 rerun
```

**Comment by sallner** [comment] 2020-08-06 06:17
That is an interesting point, I have not thought about yet. 

Regardless of what we do, when the seed is set in the beginning of a pytest run, then it should also be changed deterministically in further runs. This would go with the expectation that a seed allows for only one possible path and actually may catch some errors by making them reproducible. 

I also do not know without deeper contemplation, where we should change the seed.

@The-Compiler Do you have an opinion about that?

**Comment by The-Compiler** [comment] 2020-08-06 07:19
IMHO we shouldn't change the seed - it doesn't really seem like the responsibility of this plugin, and it seems rather confusing to me. If a test sets a given random seed to make things reproducible and then fails for some unrelated reason, then it'd be quite unexpected for pytest-rerunfailures to override that.

Then again, I've never tested anything involving the `random` module, so I don't really have a strong opinion on this.

**Comment by caiolopes** [comment] 2020-08-06 13:09
I don't have a strong opinion about that too, but to illustrate a better example then my dummy one in the issue, here it is.

I faced this issue recently with the following situation.

Someone used `choice` in the middle of a test in a project I am working with. Something like that:

```python
from random import choice

result = myfunc()  # it returns a dict with keys X, Y, Z with the all same values: N
keys = ['X', 'Y', 'W']
key = choice(keys)

assert result[key] == N
```

So, it turned a failed test if the assertions were like:

```python
for key in keys:
    assert result[key] == N
```

Into a flaky one, that only failed when key W was retrieved. But this lib reruns the test and always grab the same wrong key, so it didn't made the "flaky" test pass. But if we rerun the entire suite and changes the seed, it has a chance of passing.

Since one of the goals here is kind of trying to make flaky tests pass without needing to rerun the entire test suite, and randomness can be one of the causes, maybe is something worth to change during the rerun?

But I admit, it was a really bad test :P

**Comment by The-Compiler** [comment] 2020-08-13 09:58
IMHO, pytest-rerunfailures should be a last-resort option to deal with tests where flakiness that can't be fixed properly (often due to e.g. complex external libraries or devices/services).

In cases like this, where there's an obvious proper fix for the test (setting the random seed), I don't think pytest-rerunfailures should try to attempt a (much worse) workaround.

Thus, with that example, I'm now -1 on this :)

**Comment by caiolopes** [comment] 2020-08-13 12:20
Makes sense @The-Compiler ! Thanks for the discussion. Can I close this issue?

**Comment by The-Compiler** [comment] 2020-08-13 12:38
I'm closing this then - thanks for the suggestion anyways! :+1:

**Closed by The-Compiler** 2020-08-13 12:38 UTC
